### ISSUE TITLE
Oculus HMD Failed

### ISSUE THREAD

**Issue by Shelkey** [ohgodhowdidthis/trance#1]
I have a DK1, but it doesn't seem to get picked up by this software, and gives me "Oculus HMD Failed" as an error. Interesting project though.

Btw, I'm on the second latest version, the latest version wasn't using my text file, but had the same HMD error.

**Comment by James-Slam** [comment]
Nvm

**Comment by Shelkey** [comment]
Fixed by using Oculus Runtime.
