### ISSUE TITLE
Feature request - weighted combinations of themes?

### ISSUE THREAD

**Issue by VickyPetal** [ohgodhowdidthis/trance#2]
Hello! I have organized my images into a number of themes, based on category, so that I can combine them for programs in specific mixes of those themes. However, because images are picked uniformly across the set of all included themes, I have no control over the _ratio_ of mixing - if I want to adjust the proportion of one theme to another, I can only indirectly control this by removing images from one of the themes so that the total proportion is tweaked.

This is suboptimal, especially as it means that the only way to reduce the proportion of images shown in a particular category relative to another is to also reduce the _variety_ in that category, and also requires fiddling over exactly which images to remove vs others. 

If it were possible to construct programs by weighted combinations of themes rather than simply uniform mixes - so that, say, you would pick an image or animation from Theme 1 25% of the time, and an image from Theme 2 75% of the time - in an easily adjustable fashion, this would be greatly superior.

Would this be easily doable?

**Comment by ohgodhowdidthis** [comment]
> However, because images are picked uniformly across the set of all included themes

This isn't actually true. Currently the way it works is at any given time there are two themes "active" (primary and secondary) which are chosen uniformly from the possibilities based on the current program. Each of the active themes has an equal number of images loaded into memory based on system settings. The different kinds of visuals then pick randomly from either the primary or secondary or both in various patterns. Overall this should mean the themes are weighted evenly - adding more images to one doesn't make it more likely to see images from that theme.

Nevertheless adding a weight in case you want one theme to actually be active more often shouldn't be difficult.

**Comment by VickyPetal** [comment]
> adding more images to one doesn't make it more likely to see images from that theme.

Ah, I didn't know that! Thank you. I'd just assumed it did, which I suppose is why I found it so frustrating to try and adjust the relative frequencies by doing that.

**Comment by ohgodhowdidthis** [comment]
I have added a theme weights option as well, anyway.
